index.js
1. Use process.cwd() so db folder is looked for in root of user's application (rather than where the massive-js module is under node_modules)
2. Catch error when reading list of dirs under db if db doesn't exist
Hope these are okay.
=> Couple of fixes to finding db folder:

lib/table.js, test/db/schema.sql, test/table_spec.js
Related to #26.
This PR makes the table API functions; count, where, save, destroy, search, play nicely when our DB objects are non PG idiomatically cased.
=> Updating table API to be happier with non pg-idiomatic casing

lib/scripts/tables.sql
When foreign keys and unique constraints were present, the primary key would be incorrect.
=> Correctly get Primary Key when loading tables

index.js
This change will allow massive to work with node 0.10 (and probably lower as well).
`path.extname` and `path.basename` provide the same functionality as `path.parsed`. For more details see
docs for node 0.12:
https://nodejs.org/api/path.html
docs for node 0.10:
https://nodejs.org/docs/v0.10.35/api/path.html
=> replace path.parsed with path.extname and path.basename

lib/runner.js
This will allow users to manually clear the pg client pool.
On my case, it helps to prevent my test suite from hanging. But it might also help solve issues like #105 without having to exit the process.
=> expose pg.end to close connections immediately

lib/arg_types.js
Functions in `lib/args_types.js` use the reserved word `arguments` as a variable name which results in a syntax error when running in strict mode. Renamed the variable to `args` (in line with other functions in the library) in order to support strict mode.
=> Fix syntax error in strict mode.

lib/queryable.js, test/load_filter_spec.js, test/loader_spec.js, test/queryable_spec.js
Fixes #159 
also makes a couple other tests use the connection string in helpers to avoid having to change that multiple places.
=> fix exception when finding by a string primitive pk

lib/document_table.js, test/document_update_spec.js, test/helpers/index.js
Make use of Postgresql 9.5's jsonb_set to update a document attribute.
Will append if key is not found -- may need to revisit this default behavior.
=> Document setAttribute to update document using Postgresql 9.5's jsonb_set

lib/document_table.js, lib/where.js, test/document_update_spec.js
I'm still getting two test failures in the function loader test (& the sync version) where it's reporting an extra function being loaded. Since I just upgraded my system to 9.5, I suspect that's probably the cause -- I'd appreciate it if someone else could pull it down and confirm, juggling versions with homebrew is no fun at all.
=> fix backwards-compatibility for node < 4, fix test pollution

test/document_update_spec.js
I've noticed that errors returned in callbacks are generally ignored in the tests. This can make it hard to work out why a test is failing.
Here's the output of a currently failing test:
```
1) Document updates, Save data and update, updates the document:
Uncaught TypeError: Cannot read property 'vaccinated' of null
at Object.next (test/document_update_spec.js:30:25)
at Object.next (lib/document_table.js:131:12)
at null.callback (lib/runner.js:53:16)
at Query.handleError (node_modules/pg/lib/query.js:106:17)
at null.<anonymous> (node_modules/pg/lib/client.js:171:26)
at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
at readableAddChunk (_stream_readable.js:146:16)
at Socket.Readable.push (_stream_readable.js:110:10)
at TCP.onread (net.js:523:20)
```
It's trying to access a …
=> Add error checks to tests

test/document_update_spec.js, test/helpers/versions.js, test/loader_spec.js
* Checks the Postgres version on startup
* Initial check uses `sync` methods to avoid callback order issues
* Uses Mocha's `skip` method to skip tests
* Still need to document 9.5-only features as a separate task
* Travis tests now passing :+1: 
Fixes #189
=> Run 9.5 tests conditionally based on Postgres version

lib/table.js, test/table_spec.js
Proposed fix for #166.
When there are no fields included in an update, just return the matching records without attempting an update.
An alternative approach would be to just return an error when there are no fields to update. Let me know which option sounds best.
=> Fix update when no fields are passed

lib/runner.js
Currently the query runner error contains only a `message` property which makes it really hard to create error specific handlers. (such as a duplicate error, foreign key constraint etc.)
Looking through the commit history I saw that this was a side-effect of stacktrace improvement done back in august. By simply extending the error object we get to keep both the useful stack and all the other properties.
=> Query runner error details added

lib/scripts/functions.sql
With DB that has 600+ functions it took 2 seconds to connect to DB, most of the time is spent executing query to get functions (to be more specific most expensive was counting number of  function arguments).
With this (updated) query it now takes ~200ms.
=> Faster query to get list of DB functions

index.js, lib/scripts/functions.sql, test/load_filter_spec.js
It's really tedious to blacklist functions, especially if there are a lot of them - the list is growing very fast and has to be updated frequently.
It's much easier to move all functions to a separate schema (eg. "api") and whitelist all functions in this schema:
`massive.connectSync({connectionString : connectionString, functionWhitelist: 'api.%'})`
This PR adds whitelist functionality along with blacklist, so you can use both for fine grained filtering of functions.
=> add support for whitelisting functions

package.json
Fixes the Node 6.0.0 issue (https://github.com/brianc/node-postgres/issues/1000) which I was experiencing with a Node v6 test app on Heroku.
All tests still pass with this latest version of pg
=> Updated node-postgres dependency to v4.5.5 for a Node 6 issue

docs/functions.md, lib/executable.js, test/db/multiple_args.sql, test/function_spec.js, test/loader_spec.js
I was calling a SQL function, and started with a single argument, then went to add a second argument and it stopped working.  I thought it was a bug in massive-js but after some investigation it found that it really wasn't.  It was even documented that way.
Anyhow, I'm not sure why it was implemented that way:  naked for single value, array for more than one.  I added the ability to allow multiple arguments to be passed in without it needing to be an array, but also made sure that if they ARE passed in as an array that it doesn't break.
See test code.
I'm hoping you'll like this change OK.  I think it's cleaner in that it won't surprise the user -- this way the usage has the same signature, regardless if it's 0, 1, or N arguments that you're passing in.
I hope I'm not missing something, …
=> allow multiple arguments to be passed in naked

README.md
If you pass 1 instead of [1] it says: Error: You need to wrap your parameter into an array.
=> Example was not working

lib/arg_types.js, lib/document_table.js, lib/where.js, test/document_query_spec.js
This is in order to do a full text search in addition to filtering on e.g. 
`db.docs.searchDoc({
keys : ["title"],
term : "Document"
}, {order: 'id desc'}, {is_good: true}, function(err, res){
....
})`
The code is not beautiful, and i'm guessing there is a better way to reuse `getWhereForDoc` so that we don't have to do all that replacing, and I would be happy to implement that, if anyone could point me in the right direction.
=> Added possibility to pass conditions to searchDoc

lib/table.js
When updating a object, columns names are retrieved with _.omit
Underscore omit also returns functions names from object ( see https://gist.github.com/lfreneda/1100ecfedf7a2bec7cc527a0b0bde69c )
I'm omitting not only pk column/property but also functions/methods
based on issue 206 ( https://github.com/robconery/massive-js/issues/260 )
=> Omtting functions as column names when updating (_.omit)

docs/connecting.md, docs/functions.md, index.js, lib/executable.js, lib/scripts/functions.sql, test/db/schema.sql, test/function_spec.js, test/helpers/index.js
Hey again; this time I actually have a proof of concept!
I thought it would be nice to extend massive so that when you call an SQL function that returns, say, an integer; that you get an integer result. e.g. if you had this function:
```sql
create function myschema."getRandomNumber"()
returns integer as
$$
select 4; -- chosen by fair dice roll.
-- guaranteed to be random.
$$ language sql;
```
Currently calling that in massive will give `[{getRandomNumber: 4}]`:
```js
db.myschema.getRandomNumber((err, res) => {
assert.deepEqual(res, [{getRandomNumber: 4}]);
});
```
This PR changes that such that you instead get simply `4`:
```js
db.myschema.getRandomNumber((err, res) => {
assert.equal(res, 4);
});
```
I've done it in as minimally invasively a way as I can achieve; but that means that …
=> Function return types

package.json
vulnerability in old glob version with minimatch: https://nodesecurity.io/advisories/118
=> upgrade glob version

index.js, lib/scripts/descendant_tables.sql, lib/scripts/tables_inherits.sql, test/inheritance_spec.js
We were in need to use descendant table in Massive.
It follows the job started in https://github.com/robconery/massive-js/pull/304 and described in https://github.com/robconery/massive-js/issues/303
We have added a new `loadInheritsTables` which use an external sql file to find child and parent tables. If the parent table is already defined in Massive, we can safely add the child.
We used `pg_catalog.pg_inherits` to find these information.
=> Load descendant tables

lib/document_table.js, test/document_update_spec.js
Calling setAttribute like so:
`db.list.setAttribute(id, "children", children, [1,2,3], function(){})`
Results in the following error in the current version
`Error: invalid input syntax for type json`
The following PR resolves this and adds tests to ensure setAttribute works with arrays.
=> Added support for arrays in setAttribute

lib/operations_map.js
Could you please add two jsonb operator `?|` and `?&`? As they works only for array of strings we can use yours literalize array mutator.
These two operators used when you need to check if any or all array strings exist as top-level keys in jsonb object. See table 9-41 here:
https://www.postgresql.org/docs/9.5/static/functions-json.html
=> Jsonb text array operators

lib/queryable.js
This adds an additional check for the existence of res and res.count.
A bug in my application lead me to encounter this error in massive. With Postgres 9.4.1, if you call __count__ with and offset option, then res.count is not defined.
$ node --version
`v7.5.0`
$ psql --version
`psql (PostgreSQL) 9.4.1`
$ cat bug.js 
```
#!/usr/bin/env node
const Massive = require('massive')
const config = require('../src/js/server/config')
const db = Massive.connectSync({ connectionString: process.env.DATABASE_URL || config.database_url })
db.saveDoc('test', { something: 1 }, (err) => {
db.test.count({}, { offset: 1 }, (err, data) => {
if (err) {
console.error(err)
}
console.log(data)
process.exit(0)
})
})
```
$ ./bug.js 
```
/app/node_modules/massive/lib/queryable.js:78
else args.next(null, res.count); …
```
=> fix an error when res.count is not defined.

bin/massive.js
My repl failed silently when trying to connect to a remote Heroku database because the default database URL doesn't not force SSL which is required when connecting from outside Heroku. This change at least forces an error.
=> Add error handling to initial connection in repl

lib/table.js
Due to how underscore lib works, `_.each`, `_.map` ... methods have problems iterating objects containing a "length" property. (https://github.com/jashkenas/underscore/issues/2407)
For example this insert query fails with a `INSERT has more expressions than target columns` error:
```
massive.table.insert([{
name: 'foo',
length: 123
}, {
name: 'bar',
length: 456
}]);
```
Iterating object keys array instead of the object fixes the problem for insert.
I didn't try the update method but I'm guessing the same thing happens there too as the object is iterated by `_.each`. I'm not sure if this was done intentionally for some reason, so I wanted to check with you first.
=> length property insert bug fixed

index.js
**typeof(undefined)** results in string form of `'undefined'`.  The comparison should be done with string.
Fixes #351
=> Added fix where **undefined** comparison failing

.gitignore, docs/simple_queries.md, lib/operations_map.js, lib/where.js, test/document_query_spec.js, test/foreign_table_spec.js, test/queryable_spec.js, test/where_spec.js
It is nice to have the option to explicitly use IS/IS NOT comparison. The main reason to have that option is to distinguish between the following WHERE clause when querying documents:
1. `SELECT * FROM "docs" WHERE body @> '{"field": null}'`
2. `SELECT * FROM "docs" WHERE (body ->> 'field') IS NULL`
See below summary of changes:
- Add explicit call for IS/IS NOT in predicate (for document or not)
- Add unit testing (for IS/IS NOT null)
=> explicitly using IS or IS NOT comparison

docs/options.md, docs/persistence.md, lib/database.js, lib/statement/insert.js, test/statement/insert.js
As discussed in #425, this adds a boolean `onConflictIgnore` option to append an `ON CONFLICT DO NOTHING` clause to a generated INSERT statement. 
The `ON CONFLICT UPDATE` variant is a bit more involved so I thought I'd push this first to get some feedback.
Where should these options be documented?
=> Add onConflictIgnore option for INSERT

package.json
Updating version of [pg-promise] to one that requires a newer [pg-minify] which no longer swallows nested multi-line comments in SQL, reporting them as errors.
[pg-promise]:https://github.com/vitaly-t/pg-promise
[pg-minify]:https://github.com/vitaly-t/pg-minify
=> pg-promise update

index.js, lib/database.js
Opens the possibility to use the Database class directly without losing some of the loader functionality.
In the future, I plan on opening another PR where I would attempt to expose the `Database` class from `lib/database.js` as an importable entity, so that you may do:
```js
import { Database } from 'massive-js'
class massive = new Database(connection, loader, driverConfig)
// muuuch later, both in code and in time...
await massive.reload()
```
> I have a use case where I need to initialise the Database instance first and only much later do an actual database connection.
=> Move loader normalisation into Database class

lib/util/docify.js, test/queryable/findDoc.js, test/util/docify.js
=> findOne({}, {single: true}) should not throw (#451)

README.md
Updated the readme to clarify the section referring to upserting via the SaveDoc command.
=> Updated README to clarify behaviour of SaveDoc.

docs/options.md
Link pointed to `/documents`, which is a 404
I'm not 100% positive, but I think the intended destination was https://dmfay.github.io/massive-js/documents, which might mean the link should point to `/massive-js/documents`
=> fixed broken link to /documents

docs/options.md, docs/persistence.md, lib/statement/insert.js, test/statement/insert.js
Option to skip deep insert - this will allow storage of nested json objects.
=> Optional deep insert

docs/api/lib_statement_where.js.html, lib/statement/where.js, test/helpers/scripts/data-docs/schema.sql, test/queryable/findDoc.js, test/statement/where.js
This fixes bug #563. The same changes as PR #564 but for v4.
See below summary of changes:
* Change date casting from `timestamp` to `timestamptz`
* Add unit testing (for casting timestamp with timezone properly)
=> Fix timestamp casting for v4

lib/scripts/tables.sql, lib/table.js, test/connect.js, test/database/lists.js, test/helpers/scripts/updatables/schema.sql, test/loader/tables.js, test/table/foreign-tables.js, test/table/inheritance.js, test/table/save.js, test/table/update.js
This seems to trip people up a lot, and between the connecting user and blacklists/whitelists we already have two things that affect what actually gets loaded. Plus, better error messaging.
=> remove primary key requirement for loading tables

lib/executable.js, lib/queryable.js, lib/statement/insert.js, lib/statement/select.js, lib/table.js, lib/util/decompose.js, test/queryable/findDoc.js
This fixes bug #579 .
See below summary of changes:
* Use `hasOwnProperty` from Object prototype
* Add unit testing (by creating object with `Object.create(null)`)
=> Fix has own property issue for v4

lib/statement/where.js, test/statement/where.js
Currently with Massive, it's impossible to refer to a single column multiple times in a criteria object, for example, to represent the clause: `where blah not like 'abc%' and blah not like 'def%'`. This change introduces a new "and" key in criteria, like the "or" key, that generates a nested conjunction clause (like how the "or" key generates a nested disjunction).
=> Added special key for nested conjunctions

lib/statement/mutators.js, package-lock.json, test/statement/mutators.js
When you do something like this:
```connection.some_table.find({ whatever: new Date() })```
it needs to generate SQL like this:
```select * from some_table where whatever = $1::timestamptz```
or else Postgres blows up thinking that the date is a string.
=> Timestamp casting
