index.js

fix for missing quoting of function identifiers

---

lib/table.js
test/db/schema.sql
test/table_spec.js

Support array fields in insert and return multiple rows if need be

---

lib/table.js
test/table_spec.js

destroy with empty args object clears out table

---

lib/table.js
test/table_spec.js

My fix for #83 flattened arrays in `fields` as well -- not good :(

fix bug with updating array fields

---

lib/runner.js
lib/table.js
package.json
test/table_spec.js

integrate pg-query-stream to allow find() to return streams

---

lib/table.js
test/table_spec.js

use findArgs style for count()

---

README.md
lib/where.js
test/db/schema.sql
test/function_spec.js
test/table_spec.js

compare JSON values in WHERE clauses

---

docs/crud.md
docs/files_as_functions.md
docs/functions.md
docs/index.md
docs/simple_queries.md

@robconery @xivSolutions I had a little time over the last couple days, so I went over what was already there and added stuff about functions/scripts. Check it out and pull it in if it looks good!

some more documentation

---

index.js
lib/entity.js
lib/executable.js
lib/queryable.js

Executables

---

index.js
package.json

Use strip-bom to get rid of a UTF Byte Order Mark

---

lib/scripts/views.sql
test/db/schema.sql
test/load_filter_spec.js
test/queryable_spec.js

well, that turned out to be pretty straightforward! Fixes #177 .

support materialized views

---

docs/quick_start.md

fix a typo

---

.travis.yml
package.json
test/helpers/index.js

Resolves #128. I had to tweak the test code a bit to get it to run, but nothing major. You can see the build results [here](https://travis-ci.org/squarejaw/massive-js).

Setup Travis

---

README.md

Document global installation for using the REPL

---

docs/full_text_search.md

Uses examples from existing README.
Relates to #109

Create initial docs file for full text search

---

README.md
bin/massive.js
index.js
lib/arg_types.js
lib/document.js
lib/document_table.js
lib/entity.js
lib/executable.js
lib/queryable.js
lib/table.js
package.json
test/document_query_spec.js
test/document_save_spec.js
test/function_spec.js
test/helpers/index.js
test/load_filter_spec.js
test/loader_spec.js
test/schema_document_save_spec.js
test/schema_spec.js
test/sync_spec.js
test/table_spec.js
test/where_spec.js

* Introduces [eslint](http://eslint.org/) to help with code consistency and spotting easy to fix errors
* Starting out with the basic [recommended](http://eslint.org/docs/user-guide/migrating-to-1.0.0.html) ruleset
* Requires semi colons as they appear almost everywhere in the existing code
* Most of the fixes in this PR are unused variables
* Would be good to work out if single/double quotes are preferred. There's a real mix at the moment.
* Spacing around functions also varies quite a bit, would be good to pick a rule.

Use eslint to lint project

---

test/document_query_spec.js
test/document_save_spec.js
test/document_update_spec.js
test/function_spec.js
test/helpers/index.js
test/load_filter_spec.js
test/query_file_spec.js
test/queryable_spec.js
test/schema_document_query_spec.js
test/schema_document_save_spec.js
test/schema_spec.js
test/table_spec.js

Following on from #192, this adds error checks into all async tests.
PR's a bit huge but it's just a simple change.

Add error check to all async tests

---

.gitignore
README.md
package.json

* Generates coverage stats and a HTML report (`open coverage/lcov-report/index.html`)
* Will help identify potential test improvements
Current stats aren't too bad:
```
=============================== Coverage summary ===============================
Statements   : 93.47% ( 630/674 )
Branches     : 83.82% ( 228/272 )
Functions    : 94.12% ( 80/85 )
Lines        : 94.95% ( 620/653 )
================================================================================
```
Can add automated reporting once the project is enabled in Travis.

Use Istanbul for test coverage report

---

package.json

Update license in package.json to remove SPDX warning

---

.eslintignore
lib/queryable.js

Relates to https://github.com/robconery/massive-js/issues/183

No default limit, no default offset, adding .eslintignore

---

lib/runner.js
test/table_spec.js

add 'code' and 'detail' values to query error

---

README.md

Add missing comma to README

---

docs/document_queries.md
docs/simple_queries.md
lib/arg_types.js
lib/document_table.js
lib/query_options.js
lib/queryable.js
lib/where.js
test/db/schema.sql
test/document_query_spec.js
test/document_update_spec.js
test/load_filter_spec.js
test/loader_spec.js
test/queryable_spec.js
test/where_spec.js

Fixes #233, documents #234 and query options in general; also a bonus fix for setAttribute and string values.

Document query options

---

lib/document_table.js
test/document_save_spec.js

stop saveDoc from altering the original object reference

---

docs/document_queries.md
lib/arg_types.js
lib/document_table.js
test/document_query_spec.js

This is a use case I have. If I've there is anything that needs improvement I'm happy to fix it.

add support for limit and offset on searchDoc

---

lib/table.js
test/table_spec.js

Fixes #242 , also bubbles up "should be called with data" error instead of throwing

prevent syntax error when bulk inserting no data

---

docs/simple_queries.md
lib/operations_map.js
lib/where.js
test/queryable_spec.js
test/where_spec.js

support pattern-matching operators, better op parsing

---

index.js
lib/runner.js
test/connect_spec.js

fixes #240 
@robconery we never did come to a conclusion about what should happen with connect/init errors in #104 . When I was writing tests for the connect stuff it just made more sense to bubble things up consistently, but it _is_ a significant difference from how it worked before. Thoughts?

pass defaults through to pg, bubble connect errors

---

lib/arg_types.js
lib/query_options.js
test/document_query_spec.js
test/query_options_spec.js
test/queryable_spec.js

generate ORDER BY clauses from arrays of sort defs

---

lib/document_table.js
lib/where.js
test/document_query_spec.js
test/where_spec.js

generate a 1=1 WHERE if an empty conditions block is supplied

---

docs/simple_queries.md
lib/where.js
test/where_spec.js

fixes #269 , at least for the easy cases.

support simple casting

---

lib/arg_types.js
lib/document_table.js
lib/query.js
lib/queryable.js
lib/table.js
test/db/schemata/inheritance.sql
test/inheritance_spec.js
test/query_spec.js
test/queryable_spec.js

Basic support for table inheritance

---

lib/table.js
test/queryable_spec.js

Pretty much the same functionality that was added in the following PRs.
https://github.com/robconery/massive-js/pull/255
https://github.com/robconery/massive-js/pull/238

Added possibility to pass options and where to search.

---

lib/document_table.js
test/document_update_spec.js

update multiple document attributes in a single call

---

README.md

This isn't necessary then.. Given your last comment

Moving back to just "npm i massive --save"

---

README.md

To show it's returning a single object.

Change variable name in findOne example

---

lib/loader/scripts.js

track loaded QueryFiles to avoid reloading duplicates

---

docs/documents.md
lib/query/isPkSearch.js
lib/table.js
test/document/modify.js
test/query/isPkSearch.js

support criteria objects in table.modify

---

.gitignore
docs/criteria.md
lib/query/mutators.js
lib/query/operations.js
lib/query/where.js
test/query/mutators.js
test/query/where.js
test/queryable/countDoc.js
test/queryable/find.js
test/queryable/findDoc.js
test/queryable/search.js

explicitly using IS or IS NOT comparison v3

---

lib/database.js
lib/entity.js
lib/queryable.js
test/database/reload.js
test/entity.js
test/helpers/scripts/multi-schema/schema.sql

Fixes #438. Think it needs some more tests but just putting this out there for early review.

Query for current_schema instead of assuming 'public'

---

lib/loader/scripts.js
package.json

Corrects this PR: https://github.com/dmfay/massive-js/pull/446

upgrading to pg-promise 6.5.0

---

lib/util/decompose.js
test/queryable/decomposition.js

Decompose should preserve ordering of query results

---

package.json

fix(package): update pg-promise to version 7.5.2

---

package.json

fix(package): update pg-promise to version 8.1.1

---

test/helpers/index.js
test/queryable/find.js

Made the test import explicit, just for one test file.
Would help the future contributors to understand the file dependencies.
Just made this one change, to see if you would accept something like that, in principle.
Probably needs to be changed in other places too for consistency.
All test pass.

V5 test polish

---

docs/criteria.md

docs: add syntax for IN operator to criteria docs

---

docs/documents.md
lib/database.js
lib/writable.js
test/database/saveDocs.js

* Add saveDocs methods for saving multiple jsonb documents

feat: add saveDocs method for multiple docs(resolves #318)
